services:
  - type: web
    name: video-sniff
    runtime: node
    buildCommand: npm install && PLAYWRIGHT_BROWSERS_PATH=0 npx playwright install chromium && PLAYWRIGHT_BROWSERS_PATH=0 npx playwright install-deps chromium
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: 0
